<template>
  <div class="container">
    <div class="footer-block">
      
      <div class="footer-block_left-items">
        <div class="left-item">
          <div class="left-item_title">Platform</div>
          <div class="left-item_link">Investment Products</div>
          <div class="left-item_link">Equity Offering</div>
          <div class="left-item_link">About the Platform</div>
        </div><div class="left-item">
          <div class="left-item_title">Company</div>
          <div class="left-item_link">About</div>
          <div class="left-item_link">Roadmap</div>
          <div class="left-item_link">Contacts</div>
        </div><div class="left-item">
          <div class="left-item_title">Partnership</div>
          <div class="left-item_link">Asset Managers</div>
          <div class="left-item_link">Continuous Contributors</div>
          <div class="left-item_link">Affiliates</div>
        </div><div class="left-item">
          <div class="left-item_title">Support</div>
          <div class="left-item_link">FAQ</div>
          <div class="left-item_link">Ask a Question</div>
          <div class="left-item_link">Legal Documents</div>
        </div>
      </div>
      
      <div class="footer-block_right-items">
        <div class="right-items_top">
          
          <div class="logo">
            <img src="../assets/Logo.svg" alt="">
          </div>
          
          <div class="btn btn-check" @click="goTo('/register');">Регистрация</div>
                
          <div class="btn btn-entrance" @click="goTo('/login');">
            <img class="entrance-img login_hover" src="../assets/login_hover.svg" alt="">
            <img class="entrance-img login_activ" src="../assets/login.svg" alt="">Вход
          </div>
          
        </div>
        
        <div class="right-items_text">
          BitSmart - это структура построенная на основе блокчейн которая позволяет диверсифицировать свой портфель одним щелчком.
        </div>
      </div>
      
    </div>
    <div class="footer-block_text">
      Due to the fact that cryptocurrency markets are unregulated and decentralized, the provision of our services is not governed by any specific regulatory framework or investor protection rules. Investment in cryptocurrencies carries high degree of risk and volatility and is not suitable for every investor; therefore, you should not risk the capital you cannot afford to lose. Please consult an independent professional financial or legal advisor to ensure the product meets your objectives before you decide to invest. Under no circumstances shall Blackmoon have any liability to any person or entity for (a) any loss or damage in whole or part caused by, resulting from, or relating to any transactions related to the asset tokens or (b) any direct, indirect, special, consequential or incidental damages whatsoever. <br>
Please consider our Risk Disclosure and our Terms of Use before using our products. Social media posts about Blackmoon platform are generated by members of Blackmoon community and do not contain advice, recommendations or solicitation on behalf of Blackmoon. You are not permitted to use, alter or reproduce or distribute any of Blackmoon images and/or content, including but not limited to text, graphics, video, audio, software code, interface design or logos without our prior written consent. <br>
Security Capabilities & Policy for Transmission of Payment. <br>
All rights reserved © — Blackmoon Financial Group 2019. <br>
Blackmoon VF Ltd, a company with registration number C 87562, Level 3, Suite 2216, Tower Business Center, Tower Street, Swatar BKR 4013, Malta
    </div>
  </div>
  
  
</template>

<style lang="less" scoped>
@import '../main.less';

.footer-block {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  flex-wrap: wrap;
  border-top: 2px solid rgba(255, 255, 255, 0.1);
  border-bottom: 2px solid rgba(255, 255, 255, 0.1);
  padding-top: 65px;
  padding-bottom: 75px;
  margin-bottom: 35px;
}
.footer-block_left-items {
  max-width: 800px;
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  flex-wrap: wrap;
}
.footer-block_left-items .left-item_title {
  font-family: Relaway, sans-serif;
  font-weight: bold;
  font-size: 14px;
  color: #fff;
  margin-bottom: 18px;
}
.footer-block_left-items .left-item_link {
  font-family: Relaway, sans-serif;
  font-weight: 300;
  font-size: 12px;
  line-height: 10px;
  color: #fff;
  margin-bottom: 14px;
  cursor: pointer;
}
.footer-block_left-items .left-item_link:last-child {
  margin-bottom: 0px;
}
.footer-block_left-items .left-item_link:hover {
  color: #3753a6;
}
.footer-block_right-items {
  max-width: 340px;
}
.footer-block_right-items .right-items_top {
  display: flex;
  flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
  margin-bottom: 20px;
  margin-top: -10px;
}
.footer-block_right-items .right-items_top .logo {
  width: 120px;
  cursor: pointer;
  margin-right: 15px;
  line-height: 0px;
}
.footer-block_right-items .right-items_top .logo:hover {
  opacity: 0.5;
}
.footer-block_right-items .right-items_top .btn {
  font-size: 12px;
  color: #fff;
}
.footer-block_right-items .right-items_top .btn-check {
  line-height: 29px;
  width: 115px;
  background: #4169e2;
  margin-right: 34px;
  text-align: center;
  border-radius: 50px;
  border: 1px solid #4169e2;
  cursor: pointer;
}
.footer-block_right-items .right-items_top .btn-check:hover {
  background: none;
  box-sizing: border-box;
}
.footer-block_right-items .right-items_top .btn-entrance {
  display: flex;
  align-items: center;
  cursor: pointer;
}
.footer-block_right-items .right-items_top .btn-entrance .login_hover {
  display: none;
}
.footer-block_right-items .right-items_top .btn-entrance img {
  width: 13px;
  height: 13px;
  margin-right: 5px;
}
.footer-block_right-items .right-items_top .btn-entrance:hover {
  color: #3b60d0;
}
.footer-block_right-items .right-items_top .btn-entrance:hover .login_hover {
  display: block;
}
.footer-block_right-items .right-items_top .btn-entrance:hover .login_activ {
  display: none;
}
.footer-block_right-items .right-items_text {
  font-size: 12px;
  line-height: 16px;
  color: #696b6d;
}
.footer-block_text {
  color: #696b6d;
  font-size: 8px;
  padding-bottom: 115px;
}
@media (max-width: 1169px) {
  .footer-block_left-items {
    margin-bottom: 80px;
  }
  .logo {
    width: 100% !important;
    margin-right: 0px !important;
    margin-bottom: 10px;
  }
  .logo img {
    width: 120px;
  }
}
@media (max-width: 768px) {
  .footer-block_text {
    padding-bottom: 40px;
  }
}
@media (max-width: 500px) {
  .left-item {
    width: 50%;
    margin-bottom: 30px;
  }
}

  
</style>

<script>
export default {
  name: "footerBlock",
  methods: {
    goTo(path) {
      this.$router.push({ path: path });
    }
  }
};
</script>
